### ISSUE TITLE
When Closing Software through the Home Button, Arm11 Crash

### ISSUE THREAD

**Issue by Priestyle** [H4x0rSpooky/PkmnCTRPluginFramework#1]
Hi, when I go back to home by pressing the home button and closing the software, it always gives "An exception occured - Arm11 (core 0) Translation - Section" crash. I'm using a N3DSXL with the boot.firm that was in the release. This is for Pokemon X.

Also on a side-note, can you add 60-FPS cheat? Thx so much, huge fan of your work.

**Comment by H4x0rSpooky** [comment]
This apparently happens due to the asynchronous functions which are unavoidable since they don't work without it. I'd suggest you to disable arm11 exceptions in the luma settings as this prevents the crashing (it may get stuck when closing the software though). I sadly can't change that.

The 60-FPS Codes are working fine for ORAS however not for XY (it creates movement glitches) hence it won't be added, sorry.
